import { Shop, Product, BusinessHours, DeliveryConfig, Category, PlatformSettings } from '../types';

export const DEFAULT_PLATFORM_SETTINGS: PlatformSettings = {
  platformName: 'DailyMart Hyper-Local Marketplace',
  supportEmail: 'support@dailymart.in',
  supportPhone: '+91 1800 200 4000',
  defaultDeliveryRadiusKm: 12,
  defaultCommissionRate: 5, // 5%
  defaultDeliveryFee: 25,
  minOrderAmount: 99,
  isCodEnabled: true,
  autoCancelTimeoutMins: 15,
  updatedAt: new Date().toISOString(),
};

export const DEFAULT_CATEGORIES: Omit<Category, 'id'>[] = [
  {
    name: 'Fresh Fruits & Vegetables',
    slug: 'fruits-vegetables',
    icon: '🍎',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=400&q=80',
    displayOrder: 1,
    isActive: true,
  },
  {
    name: 'Dairy, Bread & Eggs',
    slug: 'dairy-bread-eggs',
    icon: '🥛',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=400&q=80',
    displayOrder: 2,
    isActive: true,
  },
  {
    name: 'Rice, Atta & Grains',
    slug: 'rice-atta-grains',
    icon: '🌾',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80',
    displayOrder: 3,
    isActive: true,
  },
  {
    name: 'Cooking Oils & Ghee',
    slug: 'oils-ghee',
    icon: '🫒',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=400&q=80',
    displayOrder: 4,
    isActive: true,
  },
  {
    name: 'Snacks & Biscuits',
    slug: 'snacks-biscuits',
    icon: '🍪',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=400&q=80',
    displayOrder: 5,
    isActive: true,
  },
  {
    name: 'Cold Drinks & Juices',
    slug: 'cold-drinks-juices',
    icon: '🧃',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=400&q=80',
    displayOrder: 6,
    isActive: true,
  },
  {
    name: 'Tea, Coffee & Beverages',
    slug: 'tea-coffee',
    icon: '☕',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=400&q=80',
    displayOrder: 7,
    isActive: true,
  },
  {
    name: 'Cleaning & Household',
    slug: 'cleaning-household',
    icon: '🧹',
    image: 'https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?auto=format&fit=crop&w=400&q=80',
    displayOrder: 8,
    isActive: true,
  },
  {
    name: 'Personal Care & Hygiene',
    slug: 'personal-care',
    icon: '🧴',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80',
    displayOrder: 9,
    isActive: true,
  },
];

export const DEFAULT_BUSINESS_HOURS: BusinessHours = {
  monday: { open: '08:00', close: '21:00', isClosed: false },
  tuesday: { open: '08:00', close: '21:00', isClosed: false },
  wednesday: { open: '08:00', close: '21:00', isClosed: false },
  thursday: { open: '08:00', close: '21:00', isClosed: false },
  friday: { open: '08:00', close: '21:00', isClosed: false },
  saturday: { open: '08:00', close: '22:00', isClosed: false },
  sunday: { open: '08:00', close: '20:00', isClosed: false },
};

export const DEFAULT_DELIVERY_CONFIG: DeliveryConfig = {
  isDeliveryAvailable: true,
  deliveryRadius: 12,
  deliveryFee: 25,
  freeDeliveryAbove: 299,
  estimatedDeliveryTime: '25–35 min',
  deliveryModel: 'SELF',
};

export function isShopCurrentlyOpen(shop: Shop): boolean {
  if (shop.manualOverride === 'OPEN') return true;
  if (shop.manualOverride === 'CLOSED') return false;
  if (!shop.isOpen) return false;

  if (!shop.businessHours) return true;

  const now = new Date();
  const dayNames: (keyof BusinessHours)[] = [
    'sunday',
    'monday',
    'tuesday',
    'wednesday',
    'thursday',
    'friday',
    'saturday',
  ];
  const dayName = dayNames[now.getDay()];
  const schedule = shop.businessHours[dayName];
  if (!schedule || schedule.isClosed) return false;

  const currentMinutes = now.getHours() * 60 + now.getMinutes();
  const [openH, openM] = schedule.open.split(':').map(Number);
  const [closeH, closeM] = schedule.close.split(':').map(Number);
  const openMinutes = openH * 60 + openM;
  const closeMinutes = closeH * 60 + closeM;

  return currentMinutes >= openMinutes && currentMinutes <= closeMinutes;
}

export interface SeedShopTemplate {
  name: string;
  category: string;
  description: string;
  phone: string;
  address: string;
  city: string;
  pincode: string;
  rating: number;
  totalRatings: number;
  deliveryRadius: number;
  deliveryFee: number;
  minOrder: number;
  estimatedDeliveryTime: string;
  image: string;
  tags: string[];
  offsetLat: number;
  offsetLng: number;
  products: Omit<Product, 'id' | 'shopId' | 'shopName'>[];
}

export const SEED_SHOP_TEMPLATES: SeedShopTemplate[] = [
  {
    name: 'Shree Krishna General Store',
    category: 'Groceries • Daily Essentials',
    description: 'Trusted neighborhood kirana for pure staples, fresh dairy, and daily packaged goods.',
    phone: '+91 98450 12345',
    address: 'Shop #4, Main Bazaar, 2nd Cross',
    city: 'Bengaluru',
    pincode: '560038',
    rating: 4.7,
    totalRatings: 184,
    deliveryRadius: 12,
    deliveryFee: 20,
    minOrder: 99,
    estimatedDeliveryTime: '20–30 min',
    image: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=600&q=80',
    tags: ['Daily Essentials', 'Atta & Rice', 'Dairy', 'Snacks'],
    offsetLat: 0.008,
    offsetLng: 0.006,
    products: [
      {
        name: 'Aashirvaad Superior MP Shudh Chakki Atta',
        description: '100% whole wheat grain atta made with 0% maida for soft and fluffy rotis.',
        category: 'Rice & Grains',
        price: 245,
        mrp: 275,
        unit: '5 kg',
        image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 42,
        lowStockThreshold: 10,
        inStock: true,
        isFeatured: true,
      },
      {
        name: 'Daawat Rozana Gold Basmati Rice',
        description: 'Long and aromatic basmati rice suitable for everyday pulao and biryani.',
        category: 'Rice & Grains',
        price: 98,
        mrp: 115,
        unit: '1 kg',
        image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 28,
        lowStockThreshold: 10,
        inStock: true,
        isFeatured: true,
      },
      {
        name: 'Amul Taaza Homogenised Toned Milk',
        description: 'Fresh, nutritious toned milk packed in sanitized pouch.',
        category: 'Dairy',
        price: 32,
        mrp: 34,
        unit: '500 ml',
        image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 18,
        lowStockThreshold: 8,
        inStock: true,
        isFeatured: true,
      },
      {
        name: 'Fortune Sunlite Refined Sunflower Oil',
        description: 'Light and healthy cooking oil enriched with vitamins A & D.',
        category: 'Rice & Grains',
        price: 148,
        mrp: 165,
        unit: '1 L pouch',
        image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 7, // low stock test
        lowStockThreshold: 10,
        inStock: true,
      },
      {
        name: 'Tata Salt Vacuum Evaporated Iodised Salt',
        description: 'Desh Ka Namak with guaranteed iodine content for healthy family growth.',
        category: 'Household',
        price: 28,
        mrp: 30,
        unit: '1 kg',
        image: 'https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 50,
        lowStockThreshold: 10,
        inStock: true,
      },
      {
        name: 'Farm Fresh White Eggs',
        description: 'Grade-A farm eggs, cleaned and checked for quality. Rich in protein.',
        category: 'Dairy',
        price: 49,
        mrp: 58,
        unit: 'Pack of 6',
        image: 'https://images.unsplash.com/photo-1516448620398-c5f44bf9f441?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 14,
        lowStockThreshold: 5,
        inStock: true,
      },
      {
        name: 'Maggi 2-Minute Masala Noodles',
        description: 'Classic favorite instant noodles with authentic spices blend.',
        category: 'Snacks',
        price: 58,
        mrp: 60,
        unit: 'Pack of 4 (280g)',
        image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 0, // out of stock test
        lowStockThreshold: 10,
        inStock: false,
      },
      {
        name: 'Amul Salted Butter',
        description: 'Deliciously creamy butter made from pure cow and buffalo milk.',
        category: 'Dairy',
        price: 58,
        mrp: 60,
        unit: '100 g',
        image: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 22,
        lowStockThreshold: 5,
        inStock: true,
      },
    ],
  },
  {
    name: 'FreshGreen Organic Mart',
    category: 'Fresh Fruits • Farm Vegetables',
    description: 'Direct from organic farmers. Crisp, hand-picked seasonal fruits and chemical-free vegetables.',
    phone: '+91 98451 98765',
    address: 'Plot 12, Green Park Avenue',
    city: 'Bengaluru',
    pincode: '560038',
    rating: 4.8,
    totalRatings: 312,
    deliveryRadius: 12,
    deliveryFee: 15,
    minOrder: 120,
    estimatedDeliveryTime: '25–35 min',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=600&q=80',
    tags: ['Fresh Fruits', 'Vegetables', 'Hydroponics', 'Organic'],
    offsetLat: -0.012,
    offsetLng: 0.009,
    products: [
      {
        name: 'Fresh Farm Tomatoes (Hybrid)',
        description: 'Juicy, firm red tomatoes perfect for gravies, salads, and curries.',
        category: 'Vegetables',
        price: 36,
        mrp: 45,
        unit: '1 kg',
        image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 30,
        lowStockThreshold: 8,
        inStock: true,
        isFeatured: true,
      },
      {
        name: 'Fresh Red Onions (Medium)',
        description: 'Crisp and pungent red onions sorted for minimal peel waste.',
        category: 'Vegetables',
        price: 42,
        mrp: 50,
        unit: '1 kg',
        image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 45,
        lowStockThreshold: 10,
        inStock: true,
        isFeatured: true,
      },
      {
        name: 'Fresh Mountain Potatoes (Aloo)',
        description: 'Starchy golden potatoes, clean and free of sprouts.',
        category: 'Vegetables',
        price: 34,
        mrp: 42,
        unit: '1 kg',
        image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 50,
        lowStockThreshold: 10,
        inStock: true,
      },
      {
        name: 'Organic Cavendish Bananas',
        description: 'Naturally ripened, sweet and potassium-rich table bananas.',
        category: 'Fruits',
        price: 54,
        mrp: 65,
        unit: '1 kg (5-6 pcs)',
        image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 25,
        lowStockThreshold: 5,
        inStock: true,
        isFeatured: true,
      },
      {
        name: 'Crisp Royal Gala Apples',
        description: 'Sweet, aromatic red apples with crunchy texture.',
        category: 'Fruits',
        price: 155,
        mrp: 180,
        unit: 'Pack of 4',
        image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 12,
        lowStockThreshold: 5,
        inStock: true,
      },
      {
        name: 'Fresh Hydroponic Spinach (Palak)',
        description: 'Tender baby spinach leaves washed and ready for cooking.',
        category: 'Vegetables',
        price: 26,
        mrp: 32,
        unit: '250 g bunch',
        image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 15,
        lowStockThreshold: 5,
        inStock: true,
      },
    ],
  },
  {
    name: 'Ganesh Daily Mart & Kirana',
    category: 'Dairy • Bakery • Breakfast',
    description: 'Complete morning breakfast store with fresh bakery loaves, paneer, and snacks.',
    phone: '+91 98452 44556',
    address: '88, Temple Road, 4th Block',
    city: 'Bengaluru',
    pincode: '560038',
    rating: 4.5,
    totalRatings: 142,
    deliveryRadius: 12,
    deliveryFee: 25,
    minOrder: 80,
    estimatedDeliveryTime: '25–35 min',
    image: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=600&q=80',
    tags: ['Milk & Paneer', 'Fresh Breads', 'Biscuits', 'Beverages'],
    offsetLat: 0.019,
    offsetLng: -0.015,
    products: [
      {
        name: 'Amul Malai Fresh Paneer',
        description: 'Soft, melt-in-mouth cottage cheese blocks for curries and snacks.',
        category: 'Dairy',
        price: 88,
        mrp: 95,
        unit: '200 g',
        image: 'https://images.unsplash.com/photo-1631451095765-2c91616fc9e6?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 16,
        lowStockThreshold: 5,
        inStock: true,
        isFeatured: true,
      },
      {
        name: 'Britannia 100% Whole Wheat Bread',
        description: 'Healthy breakfast brown bread packed with dietary fiber.',
        category: 'Dairy',
        price: 48,
        mrp: 50,
        unit: '400 g loaf',
        image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 10,
        lowStockThreshold: 5,
        inStock: true,
      },
      {
        name: 'Mother Dairy Classic Dahi / Curd',
        description: 'Thick, creamy set curd prepared from standardized milk.',
        category: 'Dairy',
        price: 35,
        mrp: 38,
        unit: '400 g tub',
        image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 20,
        lowStockThreshold: 6,
        inStock: true,
      },
      {
        name: 'Kellogg’s Real Almond & Honey Corn Flakes',
        description: 'Crispy toasted golden corn flakes with roasted sliced almonds.',
        category: 'Snacks',
        price: 185,
        mrp: 210,
        unit: '475 g box',
        image: 'https://images.unsplash.com/photo-1584473457406-6240486418e9?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 8,
        lowStockThreshold: 5,
        inStock: true,
      },
      {
        name: 'Taj Mahal Premium Tea',
        description: 'Rich flavor and exquisite aroma from specially selected Assam tea leaves.',
        category: 'Beverages',
        price: 168,
        mrp: 185,
        unit: '250 g pack',
        image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 15,
        lowStockThreshold: 5,
        inStock: true,
      },
    ],
  },
  {
    name: 'Sai Super Market',
    category: 'Supermarket • Cleaning & Personal Care',
    description: 'Mega neighborhood supermarket stocking branded toiletries, cleaners, and snacks.',
    phone: '+91 98453 77889',
    address: 'Corner Tower, Ring Road Junction',
    city: 'Bengaluru',
    pincode: '560038',
    rating: 4.6,
    totalRatings: 420,
    deliveryRadius: 12,
    deliveryFee: 30,
    minOrder: 199,
    estimatedDeliveryTime: '30–45 min',
    image: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?auto=format&fit=crop&w=600&q=80',
    tags: ['Supermarket', 'Household', 'Detergents', 'Personal Care'],
    offsetLat: 0.034,
    offsetLng: 0.021,
    products: [
      {
        name: 'Surf Excel Matic Front Load Liquid Detergent',
        description: 'Deep stain removal liquid that dissolves faster in washing machines.',
        category: 'Household',
        price: 229,
        mrp: 260,
        unit: '1 L bottle',
        image: 'https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 18,
        lowStockThreshold: 5,
        inStock: true,
        isFeatured: true,
      },
      {
        name: 'Vim Dishwash Gel Lemon with Active Degreasers',
        description: 'Tough on stubborn oil and grease, gentle on cooking utensils.',
        category: 'Household',
        price: 155,
        mrp: 175,
        unit: '750 ml bottle',
        image: 'https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 24,
        lowStockThreshold: 5,
        inStock: true,
      },
      {
        name: 'Dettol Original Germ Protection Liquid Handwash',
        description: 'Trusted pH-balanced antibacterial formula with pine fragrance.',
        category: 'Personal Care',
        price: 115,
        mrp: 130,
        unit: '750 ml refill pouch',
        image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 30,
        lowStockThreshold: 8,
        inStock: true,
      },
      {
        name: 'Colgate Total Whole Mouth Health Toothpaste',
        description: '12-hour antibacterial defense against plaque and cavities.',
        category: 'Personal Care',
        price: 139,
        mrp: 155,
        unit: '150 g tube',
        image: 'https://images.unsplash.com/photo-1559591937-e161043236e1?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 40,
        lowStockThreshold: 10,
        inStock: true,
      },
      {
        name: 'Harpic Power Plus Disinfectant Toilet Cleaner',
        description: '10x better stain removal and removes 99.9% germs.',
        category: 'Household',
        price: 198,
        mrp: 215,
        unit: '1 L bottle',
        image: 'https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?auto=format&fit=crop&w=500&q=80',
        stockQuantity: 16,
        lowStockThreshold: 5,
        inStock: true,
      },
    ],
  },
];
